# 大專校院各系所僑生、港澳生數
https://data.gov.tw/dataset/26210

In [33]:
import pandas as pd
import plotly.express as px
pd.set_option("display.max_columns", None)
pd.reset_option('display.max_rows')
#pd.set_option("display.max_rows", None)

In [34]:
df = pd.read_csv('學3-3.僑生、港澳生數及其在學比率-以「系所」統計.csv')
df.head()

學年度 設立別  學校類別 學校統計處代碼    學校名稱      系所代碼         系所名稱 學制班別(日間)  僑生小計  僑生男  \
0  106  公立  一般大學    0001  國立政治大學  01111001         教育學系  學士班(日間)    19    2   
1  106  公立  一般大學    0001  國立政治大學  01111001         教育學系  碩士班(日間)     3    2   
2  106  公立  一般大學    0001  國立政治大學  01114005   教育行政與政策研究所  碩士班(日間)     1    1   
3  106  公立  一般大學    0001  國立政治大學  01131002  華語文教學博士學位學程      博士班     1    0   
4  106  公立  一般大學    0001  國立政治大學  01131002  華語文教學碩士學位學程  碩士班(日間)     2    0   

   僑生女  港澳生小計  港澳生男  港澳生女  僑生及港澳生數之在學比率(%)  
0   17      5     3     2            10.04  
1    1      0     0     0             6.52  
2    0      1     0     1             4.26  
3    1      0     0     0             5.26  
4    2      1     0     1             5.26

1. What is the total number of overseas student every year

In [35]:
total_number_per_year = df.groupby(['學年度'])[['僑生小計', '港澳生小計']].sum().reset_index()
total_number_per_year

學年度   僑生小計  港澳生小計
0  106  11258  13336
1  107  11565  12285
2  108  12054  10597
3  109  12755  10761
4  110  14335  11319

In [36]:
fig = px.line(total_number_per_year, x="學年度", y=["僑生小計", "港澳生小計"])
fig.show()

2. calculate the total number of overseas student(僑生及港澳生) in each department from year 106 to 110

In [37]:
students_by_department = df.groupby('系所名稱')[['僑生小計', '港澳生小計']].sum().reset_index()
students_by_department = students_by_department.assign(僑生及港澳生小計=students_by_department['僑生小計'] + students_by_department['港澳生小計'])
students_by_department

系所名稱  僑生小計  港澳生小計  僑生及港澳生小計
0                     一貫道研究所    12      0        12
1                    不動產經營學系     2      0         2
2                 不動產與城鄉環境學系    33     22        55
3     中原大學與美國天普大學商學管理雙學士學位學程     4      5         9
4                    中國大陸研究所     5      9        14
...                      ...   ...    ...       ...
1898                高齡健康管理學系     2     18        20
1899         高齡健康與運動科學學士學位學程     0      1         1
1900              高齡及長期照護事業系     0      1         1
1901              高齡服務學士學位學程     0      2         2
1902               高齡福祉養生管理系     0      1         1

[1903 rows x 4 columns]

3. Sort the total number of overseas students in ascending order.

In [38]:
students_by_department_sorted = students_by_department.sort_values('僑生及港澳生小計', ascending=False)
students_by_department_sorted

系所名稱  僑生小計  港澳生小計  僑生及港澳生小計
53            企業管理學系  1926   1433      3359
1589          資訊工程學系  1421   1485      2906
1748             醫學系  1717    471      2188
7              中國文學系   615   1113      1728
1612          資訊管理學系   864    705      1569
...              ...   ...    ...       ...
690          政治經濟研究所     0      1         1
1183  生物醫學科學系生物醫學碩士班     0      1         1
1628      資訊與決策科學研究所     0      1         1
687     政治學系政治經濟學碩士班     0      1         1
1902       高齡福祉養生管理系     0      1         1

[1903 rows x 4 columns]

In [60]:
fig = px.pie(students_by_department_sorted.head(30), values='僑生及港澳生小計', names='系所名稱')
fig.show()

4. Calculate the total number of students in each department each year.

In [70]:
total_student_by_department = df[['學年度','學校名稱', '系所名稱']]
total_student_by_department = total_student_by_department.assign(僑生及港澳生小計=df['僑生小計'] + df['港澳生小計'])
total_student_by_department = total_student_by_department.assign(僑生及港澳生數之在學比率=df['僑生及港澳生數之在學比率(%)'])
total_student_by_department = total_student_by_department.assign(系所總人數=total_student_by_department['僑生及港澳生小計'] * 100 / total_student_by_department['僑生及港澳生數之在學比率'])
total_student_by_department = total_student_by_department.round({'系所總人數': 0})
total_student_by_department = total_student_by_department.reindex(columns=['學年度', '學校名稱', '系所名稱', '僑生及港澳生小計', '系所總人數', '僑生及港澳生數之在學比率'])
total_student_by_department

學年度    學校名稱         系所名稱  僑生及港澳生小計  系所總人數  僑生及港澳生數之在學比率
0      106  國立政治大學         教育學系        24  239.0         10.04
1      106  國立政治大學         教育學系         3   46.0          6.52
2      106  國立政治大學   教育行政與政策研究所         2   47.0          4.26
3      106  國立政治大學  華語文教學博士學位學程         1   19.0          5.26
4      106  國立政治大學  華語文教學碩士學位學程         3   57.0          5.26
...    ...     ...          ...       ...    ...           ...
15760  110  臺北市立大學       技擊運動學系         3  203.0          1.48
15761  110  臺北市立大學      運動健康科學系        15  223.0          6.73
15762  110  臺北市立大學      運動健康科學系         3   33.0          9.09
15763  110  臺北市立大學     休閒運動管理學系        16  231.0          6.93
15764  110  臺北市立大學     休閒運動管理學系         2   36.0          5.56

[15765 rows x 6 columns]

5. Calculate the percentage of overseas student in each school every year

In [63]:
percentage_of_overseas_students = total_student_by_department.drop('僑生及港澳生數之在學比率', axis=1)
percentage_of_overseas_students = percentage_of_overseas_students.groupby(['學年度', '學校名稱'])[['僑生及港澳生小計', '系所總人數']].sum().reset_index()
percentage_of_overseas_students
percentage_of_overseas_students = percentage_of_overseas_students.assign(僑生及港澳生在學校比例=percentage_of_overseas_students['僑生及港澳生小計'] / percentage_of_overseas_students['系所總人數'
] * 100)
percentage_of_overseas_students = percentage_of_overseas_students.round({'僑生及港澳生在學校比例': 2})
percentage_of_overseas_students = percentage_of_overseas_students.sort_values(['僑生及港澳生在學校比例', '學校名稱'], ascending=False)
percentage_of_overseas_students

學年度                學校名稱  僑生及港澳生小計   系所總人數  僑生及港澳生在學校比例
595  110              吳鳳科技大學       213   213.0       100.00
455  109              吳鳳科技大學       151   244.0        61.89
314  108              吳鳳科技大學        56   349.0        16.05
673  110      正修學校財團法人正修科技大學       812  5113.0        15.88
42   106            國立暨南國際大學       678  5209.0        13.02
..   ...                 ...       ...     ...          ...
141  106  馬偕學校財團法人馬偕醫護管理專科學校         1  2000.0         0.05
283  107  馬偕學校財團法人馬偕醫護管理專科學校         1  2000.0         0.05
119  106          耕莘健康管理專科學校         1  3333.0         0.03
260  107          耕莘健康管理專科學校         1  3333.0         0.03
402  108          耕莘健康管理專科學校         1  3333.0         0.03

[707 rows x 5 columns]

In [76]:
fig = px.scatter(percentage_of_overseas_students.head(30), x="學校名稱", y="僑生及港澳生小計",
                 size="僑生及港澳生在學校比例")
fig.show()

6. Compare the percentage of overseas student of the NTU school system

In [32]:
ntnu_number = percentage_of_overseas_students.query('學校名稱=="國立臺灣師範大學" | 學校名稱=="國立臺灣大學" | 學校名稱=="國立臺灣科技大學"')
ntnu_number = ntnu_number.groupby(["學校名稱"])["僑生及港澳生在學校比例"].mean().sort_values(ascending=False).reset_index()
ntnu_number.columns = ['學校名稱', '僑生及港澳生106至110在學比例之平均值']
ntnu_number

學校名稱  僑生及港澳生106至110在學比例之平均值
0  國立臺灣師範大學                  6.474
1    國立臺灣大學                  5.492
2  國立臺灣科技大學                  4.552

7. Find the number of undergraduate and graduate programs that have overseas Chinese and Hong Kong/Macau students. 

In [26]:
undergrad_df = df[df['學制班別(日間)'].str.contains('學士班')]
grad_df = df[df['學制班別(日間)'].str.contains('碩士班|博士班')]
undergrad_count = undergrad_df.groupby('系所名稱')[['僑生小計', '港澳生小計']].sum().reset_index()
grad_count = grad_df.groupby('系所名稱')[['僑生小計', '港澳生小計']].sum().reset_index()
undergrad_count['學制班別'] = '學士班'
grad_count['學制班別'] = '碩/博士班'
undergrad_grad_merged = pd.concat([undergrad_count, grad_count])
undergrad_grad_merged

系所名稱  僑生小計  港澳生小計   學制班別
0                    不動產經營學系     2      0    學士班
1                 不動產與城鄉環境學系    33     20    學士班
2     中原大學與美國天普大學商學管理雙學士學位學程     4      5    學士班
3                     中國戲劇學系     9      1    學士班
4                     中國文學學系    38    126    學士班
...                      ...   ...    ...    ...
1080                   體育研究所     3      3  碩/博士班
1081               體育與健康休閒學系     0      1  碩/博士班
1082                體育與運動科學系     7      9  碩/博士班
1083            高分子科學與工程學研究所     2      1  碩/博士班
1084                高齡健康管理學系     0      2  碩/博士班

[2310 rows x 4 columns]

8. Find The ratio of overseas Chinese and Hong Kong/Macau students in different programs.

In [27]:
overseas_df = df[(df['僑生小計'] > 0) | (df['港澳生小計'] > 0)]
program_count = overseas_df.groupby('系所名稱')[['僑生小計', '港澳生小計']].sum().reset_index()
program_count['比例'] = (program_count['僑生小計'] + program_count['港澳生小計']) / (program_count['僑生小計'].sum() + program_count['港澳生小計'].sum()) * 100
program_count = program_count.sort_values('比例', ascending=False)
program_count

系所名稱  僑生小計  港澳生小計        比例
53            企業管理學系  1926   1433  2.792999
1589          資訊工程學系  1421   1485  2.416331
1748             醫學系  1717    471  1.819316
7              中國文學系   615   1113  1.436827
1612          資訊管理學系   864    705  1.304619
...              ...   ...    ...       ...
690          政治經濟研究所     0      1  0.000831
1183  生物醫學科學系生物醫學碩士班     0      1  0.000831
1628      資訊與決策科學研究所     0      1  0.000831
687     政治學系政治經濟學碩士班     0      1  0.000831
1902       高齡福祉養生管理系     0      1  0.000831

[1903 rows x 4 columns]

In [43]:
fig = px.bar(program_count.head(30), x='系所名稱', y=["僑生小計", "港澳生小計"])
fig.show()

9. Find The number of male and female overseas Chinese and Hong Kong/Macau students in different programs.

In [28]:
overseas_df = df[(df['僑生小計'] > 0) | (df['港澳生小計'] > 0)]
gender_df = overseas_df.groupby(['系所名稱']).agg({'僑生男': 'sum', '僑生女': 'sum', '港澳生男': 'sum', '港澳生女': 'sum'})
gender_df['男生總計'] = gender_df['僑生男'] + gender_df['港澳生男']
gender_df['女生總計'] = gender_df['僑生女'] + gender_df['港澳生女']
gender_df_sorted = gender_df.sort_values(['男生總計', '女生總計'], ascending=False).reset_index()
gender_df_sorted

系所名稱   僑生男  僑生女  港澳生男  港澳生女  男生總計  女生總計
0              資訊工程學系  1150  271  1306   179  2456   450
1              企業管理學系   948  978   943   490  1891  1468
2              電機工程學系   708   85   574    21  1282   106
3              資訊管理學系   653  211   586   119  1239   330
4                 醫學系   758  959   287   184  1045  1143
...               ...   ...  ...   ...   ...   ...   ...
1898         食品科學系碩士班     0    1     0     0     0     1
1899         食品科技與行銷系     0    1     0     0     0     1
1900        養生與健康行銷學系     0    0     0     1     0     1
1901  高齡健康與運動科學學士學位學程     0    0     0     1     0     1
1902       高齡及長期照護事業系     0    0     0     1     0     1

[1903 rows x 7 columns]

In [42]:
fig = px.bar(gender_df_sorted.head(30), x='系所名稱', y=["男生總計", "女生總計"], barmode="group")
fig.show()

10. Find which course is popular among male students and female students?

In [30]:
grouped = df.groupby('系所名稱').agg({'僑生男': 'sum', '僑生女': 'sum', '港澳生男': 'sum', '港澳生女': 'sum'})

grouped['male_students'] = grouped['僑生男'] + grouped['港澳生男']
grouped['female_students'] = grouped['僑生女'] + grouped['港澳生女']

grouped['total_students'] = grouped['male_students'] + grouped['female_students']

grouped['male_percentage'] = grouped['male_students'] / grouped['total_students'] * 100
grouped['female_percentage'] = grouped['female_students'] / grouped['total_students'] * 100

popular_male_courses = grouped.sort_values('male_percentage', ascending=False).index[:5]
popular_female_courses = grouped.sort_values('female_percentage', ascending=False).index[:5]

# Print the results
print(f'受男性歡迎的科系: \n{popular_male_courses}')
print(f'受女性歡迎的科系: \n{popular_female_courses}')

受男性歡迎的科系: 
Index(['歷史研究所', '機械與自動化工程系機電科技碩士班', '會計資訊系會計財稅碩士班', '會計資訊系碩士班', '材料工程研究所'], dtype='object', name='系所名稱')
受女性歡迎的科系: 
Index(['智慧生活科技學系大數據與管理碩士班', '商管專業學院碩士學位學程', '商業設計系碩士班', '商業設計學系設計創作與研究碩士班',
       '戲劇碩士學位學程'],
      dtype='object', name='系所名稱')
